// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesMovie.Data;

#nullable disable

namespace RazorPagesMovie.Migrations
{
    [DbContext(typeof(SocialHDXContext))]
    [Migration("20260413163124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("RazorPagesMovie.Models.StudentCase", b =>
                {
                    b.Property<int>("StudentCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentCaseReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentCaseStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescriberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentCaseId");

                    b.HasIndex("PrescriberId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCase");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.StudentCaseNote", b =>
                {
                    b.Property<int>("StudentCaseNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescriberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentCaseNoteId");

                    b.HasIndex("StudentCaseId");

                    b.HasIndex("PrescriberId");

                    b.ToTable("StudentCaseNote");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.CampusEvent", b =>
                {
                    b.Property<int>("CampusEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CampusEventDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CampusEventTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("CampusEventId");

                    b.ToTable("CampusEvent");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Prescriber", b =>
                {
                    b.Property<int>("PrescriberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrainedStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrescriberId");

                    b.ToTable("Prescriber");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttendanceConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("TEXT");

                    b.Property<int>("CampusEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrescriberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("CampusEventId");

                    b.HasIndex("PrescriberId");

                    b.HasIndex("StudentId");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.StudentCase", b =>
                {
                    b.HasOne("RazorPagesMovie.Models.Prescriber", "Prescriber")
                        .WithMany()
                        .HasForeignKey("PrescriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorPagesMovie.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescriber");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.StudentCaseNote", b =>
                {
                    b.HasOne("RazorPagesMovie.Models.StudentCase", "StudentCase")
                        .WithMany("StudentCaseNotes")
                        .HasForeignKey("StudentCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorPagesMovie.Models.Prescriber", "Prescriber")
                        .WithMany()
                        .HasForeignKey("PrescriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentCase");

                    b.Navigation("Prescriber");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Prescription", b =>
                {
                    b.HasOne("RazorPagesMovie.Models.CampusEvent", "CampusEvent")
                        .WithMany()
                        .HasForeignKey("CampusEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorPagesMovie.Models.Prescriber", "Prescriber")
                        .WithMany()
                        .HasForeignKey("PrescriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorPagesMovie.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampusEvent");

                    b.Navigation("Prescriber");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.StudentCase", b =>
                {
                    b.Navigation("StudentCaseNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
